[build]
  publish = "."

[[redirects]]
  from = "http://www.docs.dove365.com/*"
  to = "https://docs.dove365.com/:splat"
  status = 301
  force = true


[[redirects]]
  from = "/ai-enablement"
  to = "https://www.dove365.com/ai-enablement.html"
  status = 200

[[redirects]]
  from = "/ai-toolkit"
  to = "https://www.dove365.com/ai-toolkit.html"
  status = 200

[[redirects]]
  from = "/dove365-ai-toolkit.html"
  to = "https://www.dove365.com/ai-toolkit.html"
  status = 301

[[redirects]]
  from = "/resources/dove365-AI-readiness-assessment.html"
  to = "https://www.dove365.com/resources/AI-readiness-assessment.html"
  status = 301

[[redirects]]
  from = "/"
  to = "/docs.html"
  status = 200
